/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista.login;

import java.awt.Color;

public class Principal extends javax.swing.JFrame {

    static int click = 0;

    panelLogin login;
    panelRegistro registro;

    public Principal() {
        initComponents();
        login = new panelLogin();
        contenedor.add(login);
        jLabel6.setVisible(true);
        btnRegistrarse.setVisible(true);
        this.setSize(480, 450);
        this.setLocationRelativeTo(null);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        contenedor = new javax.swing.JPanel();
        barraOpciones = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        btnRegistrarse = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        contenedor.setLayout(new java.awt.BorderLayout());

        barraOpciones.setBackground(new java.awt.Color(51, 255, 153));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(102, 102, 102));
        jLabel6.setText("¿Aún no tienes una cuenta?");
        barraOpciones.add(jLabel6);

        btnRegistrarse.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnRegistrarse.setForeground(new java.awt.Color(51, 102, 255));
        btnRegistrarse.setText("Regístrate");
        btnRegistrarse.setToolTipText("Crear Cuenta");
        btnRegistrarse.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnRegistrarse.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnRegistrarseMouseClicked(evt);
            }
        });
        barraOpciones.add(btnRegistrarse);

        contenedor.add(barraOpciones, java.awt.BorderLayout.PAGE_END);

        getContentPane().add(contenedor, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void botones() {

        if (login.isVisible()) {

            btnRegistrarse.setVisible(true);
            jLabel6.setVisible(true);
        } else {
            if (registro.isVisible()) {
                login.setVisible(false);
                btnRegistrarse.setVisible(false);
                jLabel6.setVisible(false);
                barraOpciones.setBackground(new Color(51, 255, 153));
            }
        }
    }

    private void btnRegistrarseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRegistrarseMouseClicked
        registro = new panelRegistro();
        click++;
        if (click == 1) {
            registro.setVisible(true);
            login.setVisible(false);
            contenedor.add(registro);
            System.out.println(click);
            botones();
        }
        if (click == 0) {
            registro.setVisible(false);
            login.setVisible(true);
            contenedor.add(login);
            botones();
            System.out.println(click);

        }


    }//GEN-LAST:event_btnRegistrarseMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JPanel barraOpciones;
    public static javax.swing.JLabel btnRegistrarse;
    public static javax.swing.JPanel contenedor;
    public static javax.swing.JLabel jLabel6;
    // End of variables declaration//GEN-END:variables

}
