/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista.formularios;

import java.util.HashMap;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import modelo.BD.Conexion;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author Sammy Guergachi <sguergachi at gmail.com>
 */
public class frmReportesProductos extends javax.swing.JInternalFrame {

    /**
     * Creates new form frmReportesProductos
     */
    public frmReportesProductos() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnRProducto = new javax.swing.JButton();
        btnRProducto1 = new javax.swing.JButton();

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        btnRProducto.setBackground(new java.awt.Color(255, 255, 255));
        btnRProducto.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnRProducto.setForeground(new java.awt.Color(51, 51, 51));
        btnRProducto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/principal/reporte.png"))); // NOI18N
        btnRProducto.setText("Reporte Sin Parametros Producto");
        btnRProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRProductoActionPerformed(evt);
            }
        });

        btnRProducto1.setBackground(new java.awt.Color(255, 255, 255));
        btnRProducto1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnRProducto1.setForeground(new java.awt.Color(51, 51, 51));
        btnRProducto1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/principal/reporte.png"))); // NOI18N
        btnRProducto1.setText("Reporte Con Parametros proveedores");
        btnRProducto1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRProducto1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(btnRProducto))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(btnRProducto1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(btnRProducto)
                .addGap(57, 57, 57)
                .addComponent(btnRProducto1)
                .addContainerGap(56, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRProductoActionPerformed
        // TODO add your handling code here:
        String reporte = "./src/vista/reportes/";
        Conexion.Conectar();
        try {
            JasperReport report = JasperCompileManager.compileReport(reporte + "reportProductosVendidos.jrxml");
            HashMap parametros = new HashMap();

            JasperPrint imprimir = JasperFillManager.fillReport(report, parametros, Conexion.getConnection());
            JasperViewer.viewReport(imprimir, true);
        } catch (JRException ex) {
            ex.printStackTrace(System.out);
        }
    }//GEN-LAST:event_btnRProductoActionPerformed

    private void btnRProducto1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRProducto1ActionPerformed
        Conexion.Conectar();
        String prove = JOptionPane.showInputDialog("Ingrese nombre para buscar");
        String reporte = "./src/vista/reportes/";
        
        try {
            JasperReport report = JasperCompileManager.compileReport(reporte + "reportProvee.jrxml");
            HashMap parametros = new HashMap();
            parametros.put("nombreP",prove+"%");
            JasperPrint imprimir = JasperFillManager.fillReport(report, parametros, Conexion.getConnection());
            JasperViewer.viewReport(imprimir, true);
        } catch (JRException ex) {
            ex.printStackTrace(System.out);
        }
    }//GEN-LAST:event_btnRProducto1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRProducto;
    private javax.swing.JButton btnRProducto1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
