/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista.formularios;

import java.awt.EventQueue;
import java.awt.Graphics;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JInternalFrame;

public class ventanaContenedora extends javax.swing.JFrame {

    /**
     * Creates new form ventanaContenedora
     */
    frmProducto p = new frmProducto();

    public ventanaContenedora() {
        initComponents();
        this.setSize(1310, 700);
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ImageIcon icon = new ImageIcon(getClass().getResource("/icons/1877.jpg"));
        Image image = icon.getImage();
        desktopPane = new javax.swing.JDesktopPane(){

            public void paintComponent(Graphics g){
                g.drawImage(image, 0, 0, getWidth(),getHeight(),this);
            }

        };
        menuBar = new javax.swing.JMenuBar();
        fileMenu = new javax.swing.JMenu();
        proveedores = new javax.swing.JMenuItem();
        frmMarca = new javax.swing.JMenuItem();
        frmCategoria = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        exitMenuItem = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout desktopPaneLayout = new javax.swing.GroupLayout(desktopPane);
        desktopPane.setLayout(desktopPaneLayout);
        desktopPaneLayout.setHorizontalGroup(
            desktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 712, Short.MAX_VALUE)
        );
        desktopPaneLayout.setVerticalGroup(
            desktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 398, Short.MAX_VALUE)
        );

        getContentPane().add(desktopPane, java.awt.BorderLayout.CENTER);

        menuBar.setBorder(null);
        menuBar.setForeground(new java.awt.Color(0, 0, 0));
        menuBar.setPreferredSize(new java.awt.Dimension(179, 50));

        fileMenu.setBackground(new java.awt.Color(255, 255, 255));
        fileMenu.setForeground(new java.awt.Color(0, 0, 0));
        fileMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/principal/tienda.png"))); // NOI18N
        fileMenu.setMnemonic('f');
        fileMenu.setText("Productos");
        fileMenu.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        fileMenu.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        proveedores.setFont(new java.awt.Font("Arial", 2, 14)); // NOI18N
        proveedores.setForeground(new java.awt.Color(51, 51, 51));
        proveedores.setMnemonic('a');
        proveedores.setText("Proveedor");
        proveedores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                proveedoresActionPerformed(evt);
            }
        });
        fileMenu.add(proveedores);

        frmMarca.setFont(new java.awt.Font("Arial", 2, 14)); // NOI18N
        frmMarca.setForeground(new java.awt.Color(51, 51, 51));
        frmMarca.setMnemonic('o');
        frmMarca.setText("Marca");
        frmMarca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                frmMarcaActionPerformed(evt);
            }
        });
        fileMenu.add(frmMarca);

        frmCategoria.setFont(new java.awt.Font("Arial", 2, 14)); // NOI18N
        frmCategoria.setForeground(new java.awt.Color(51, 51, 51));
        frmCategoria.setMnemonic('s');
        frmCategoria.setText("Categoria");
        frmCategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                frmCategoriaActionPerformed(evt);
            }
        });
        fileMenu.add(frmCategoria);

        jMenuItem2.setFont(new java.awt.Font("Arial", 2, 14)); // NOI18N
        jMenuItem2.setForeground(new java.awt.Color(51, 51, 51));
        jMenuItem2.setText("Producto");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        fileMenu.add(jMenuItem2);

        exitMenuItem.setFont(new java.awt.Font("Arial", 2, 14)); // NOI18N
        exitMenuItem.setForeground(new java.awt.Color(51, 51, 51));
        exitMenuItem.setMnemonic('x');
        exitMenuItem.setText("Salir");
        exitMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitMenuItemActionPerformed(evt);
            }
        });
        fileMenu.add(exitMenuItem);
        fileMenu.add(jSeparator1);

        menuBar.add(fileMenu);

        jMenu1.setBackground(new java.awt.Color(255, 255, 255));
        jMenu1.setForeground(new java.awt.Color(0, 0, 0));
        jMenu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/principal/vender.png"))); // NOI18N
        jMenu1.setText("Vender");
        jMenu1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        jMenuItem1.setFont(new java.awt.Font("Arial", 2, 14)); // NOI18N
        jMenuItem1.setForeground(new java.awt.Color(51, 51, 51));
        jMenuItem1.setText("Nueva Venta");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        menuBar.add(jMenu1);

        jMenu2.setBackground(new java.awt.Color(255, 255, 255));
        jMenu2.setForeground(new java.awt.Color(0, 0, 0));
        jMenu2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/principal/factura.png"))); // NOI18N
        jMenu2.setText("Reportes");
        jMenu2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jMenu2.setPreferredSize(new java.awt.Dimension(149, 40));

        jMenuItem3.setText("Reporte de Productos");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem3);

        menuBar.add(jMenu2);

        setJMenuBar(menuBar);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void exitMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitMenuItemActionPerformed
        System.exit(0);
    }//GEN-LAST:event_exitMenuItemActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        cargarFormularios(new frmVenta(), "VENTA");
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void proveedoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_proveedoresActionPerformed
        // TODO add your handling code here:
        cargarFormularios(new frmProveedor(), "PROVEEDORES");
    }//GEN-LAST:event_proveedoresActionPerformed

    private void frmMarcaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_frmMarcaActionPerformed
        // TODO add your handling code here:
        cargarFormularios(new frmMarca(), "MARCAS");
    }//GEN-LAST:event_frmMarcaActionPerformed

    private void frmCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_frmCategoriaActionPerformed
        // TODO add your handling code here:
        cargarFormularios(new frmCategoria(), "CATEGORIA");
    }//GEN-LAST:event_frmCategoriaActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        EventQueue.invokeLater(new Runnable() {
            public void run() {
                JFrame frame = new JFrame();
                frame.setLocationRelativeTo(null);
                frame.setContentPane(new frmProducto());
                frame.pack();
                frame.setVisible(true);
            }
        });

    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:
        cargarFormularios(new frmReportesProductos(), "Reportes");
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ventanaContenedora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        /* Create and display the form */
        //</editor-fold>

        /* Create and display the form */
    }

    private void cargarFormularios(JInternalFrame panel, String nombre) {
        panel.setTitle(nombre);
        int ancho = ((desktopPane.getWidth() / 2) - panel.getWidth() / 2);
        int alto = ((desktopPane.getHeight() / 2) - panel.getHeight() / 2);
        panel.setLocation(ancho, alto);

        panel.setClosable(true);
        desktopPane.add(panel);
        panel.show();

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane desktopPane;
    private javax.swing.JMenuItem exitMenuItem;
    private javax.swing.JMenu fileMenu;
    private javax.swing.JMenuItem frmCategoria;
    private javax.swing.JMenuItem frmMarca;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenuItem proveedores;
    // End of variables declaration//GEN-END:variables

}
